<?php include __DIR__.'/header.phtml'; ?>

    <h1>Nous contacter</h1>

    <form action="#" method="post">
        <label for="nom">Nom :</label><br>
        <input type="text" id="nom" name="nom" required><br><br>

        <label for="prenom">Prénom :</label><br>
        <input type="text" id="prenom" name="prenom" required><br><br>

        <label for="email">Email :</label><br>
        <input type="email" id="email" name="email" required><br><br>

        <label for="message">Message :</label><br>
        <textarea id="message" name="message" required></textarea><br><br>
        
        <button type="submit">Envoyer</button>
    </form>

<?php include __DIR__.'/footer.phtml'; ?>